os: osx
osx_image: xcode10.1
language: objective-c

cache:
  bundler: true
  directories:
    - .build

stages:
  - "Prepare Cache"
  - "Test"
  - name: "Deploy"
    if: branch = master AND tag IS present

jobs:
  include:
    - stage: "Prepare Cache"
      script: swift build
    - stage: "Test"
      name: "Unit tests (SPM)"
      install: skip
      script: swift test
    - stage: "Test"
      name: "Unit tests (Xcode)"
      install: skip
      xcode_project: Shepherd.xcodeproj
      xcode_scheme:
        - Shepherd-iOS
        - Shepherd-macOS
        - Shepherd-tvOS
    - stage: "Test"
      name: "pod lib lint"
      if: type = pull_request
      script: bundle exec pod lib lint
    - stage: "Test"
      name: "Danger"
      if: type = pull_request
      install: npm install -g danger
      script: swift run danger-swift ci
    - stage: "Deploy"
      name: "GitHub Release"
      install: skip
      script: skip
      before_deploy: carthage build --archive --cache-builds --platform iOS
      deploy:
        provider: releases
        prerelease: true
        api_key: $GITHUB_TOKEN
        file: Shepherd.framework.zip
        skip_cleanup: true
    - stage: "Deploy"
      name: "CocoaPods release"
      script: skip
      deploy:
        provider: script
        script: bundle exec pod trunk push
