os: osx
osx_image: xcode10.1
language: objective-c

cache:
  bundler: true
  directories:
    - Carthage
    - .build
    - /home/travis/.rvm/

stages:
  - "Prepare Cache"
  - "Test"
  - name: "Deploy"
    if: branch = master AND tag IS present
jobs:
  include:
    - stage: "Prepare Cache"
      script:
        - npm install -g danger
        - swift build
    - stage: "Test"
      script:
        - swift test
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bundle exec pod lib lint; fi
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then swift run danger-swift ci; fi
    - stage: "Deploy"
      name: "GitHub Release"
      script: skip
      before_deploy:
        - carthage build --archive --cache-builds --platform iOS
      deploy:
        provider: releases
        prerelease: true
        api_key: $GITHUB_TOKEN
        file: Shepherd.framework.zip
        skip_cleanup: true
    - script: skip
      name: "CocoaPods release"
      deploy:
        provider: script
        script: pod trunk push
