os: osx
osx_image: xcode10.1
language: objective-c

cache:
  bundler: true
  directories:
    - Carthage
    - .build
    - /home/travis/.rvm/

stages:
  - "Prepare Cache"
  - "Test"
  - name: "Deploy"
    if: tag IS present

jobs:
  include:
    - stage: "Prepare Cache"
      script: swift build
    - stage: "Test"
      name: "Unit tests"
      script:
        - swift test
    - stage: "Test"
      name: "pod lib lint"
      if: type = pull_request
      script: bundle exec pod lib lint
    - stage: "Test"
      name: "Danger"
      if: type = pull_request
      script:
        - npm install -g danger
        - swift run danger-swift ci
    - stage: "Deploy"
      name: "GitHub Release"
      script: skip
      before_deploy:
        - carthage build --archive --cache-builds --platform iOS
      deploy:
        provider: releases
        prerelease: true
        api_key: $GITHUB_TOKEN
        file: Shepherd.framework.zip
        skip_cleanup: true
    - stage: "Deploy"
      name: "CocoaPods release"
      script: skip
      deploy:
        provider: script
        script: pod trunk push
