os: osx
osx_image: xcode10.1
language: objective-c

cache:
  bundler: true
  directories:
    - .build

stages:
  - "Prepare Cache"
  - "Test"
  - name: "Deploy"
    if: branch = master AND tag IS present

jobs:
  include:
    - stage: "Prepare Cache"
      script: swift build
    - stage: "Test"
      name: "Unit tests (macOS)"
      install: skip
      script: swift test
    - stage: "Test"
      name: "Unit tests (iOS)"
      install: skip
      xcode_scheme: Shepherd-iOS
      xcode_sdk: iphonesimulator12.1
      env: DESTINATION="platform=iOS Simulator,OS=12.1,name=iPhone XS"
      script:
        - set -o pipefail
        - xcodebuild clean build build-for-testing -project Shepherd.xcodeproj -scheme "${TRAVIS_XCODE_SCHEME}" -sdk "${TRAVIS_XCODE_SDK}" -destination "${DESTINATION}" | xcpretty
        - xcodebuild test-without-building -project Shepherd.xcodeproj -scheme "${TRAVIS_XCODE_SCHEME}" -sdk "${TRAVIS_XCODE_SDK}" -destination "${DESTINATION}" | xcpretty
    - stage: "Test"
      name: "Unit tests (tvOS)"
      install: skip
      xcode_scheme: Shepherd-tvOS
      xcode_sdk: appletvsimulator12.1
      env: DESTINATION="platform=tvOS Simulator,OS=12.1,name=Apple TV"
      script:
        - set -o pipefail
        - xcodebuild clean build build-for-testing -project Shepherd.xcodeproj -scheme "${TRAVIS_XCODE_SCHEME}" -sdk "${TRAVIS_XCODE_SDK}" -destination "${DESTINATION}" | xcpretty
        - xcodebuild test-without-building -project Shepherd.xcodeproj -scheme "${TRAVIS_XCODE_SCHEME}" -sdk "${TRAVIS_XCODE_SDK}" -destination "${DESTINATION}" | xcpretty
    - stage: "Test"
      name: "pod lib lint"
      if: type = pull_request
      script: bundle exec pod lib lint
    - stage: "Test"
      name: "Danger"
      if: type = pull_request
      install: npm install -g danger
      script: swift run danger-swift ci
    - stage: "Deploy"
      name: "GitHub Release"
      install: skip
      script: skip
      before_deploy: carthage build --archive --cache-builds --platform iOS
      deploy:
        provider: releases
        prerelease: true
        api_key: $GITHUB_TOKEN
        file: Shepherd.framework.zip
        skip_cleanup: true
    - stage: "Deploy"
      name: "CocoaPods release"
      script: skip
      deploy:
        provider: script
        script: bundle exec pod trunk push
