#if !canImport(ObjectiveC)
import XCTest

extension ShepherdTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ShepherdTests = [
        ("testExample", testExample),
        ("testPerformanceExample", testPerformanceExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ShepherdTests.__allTests__ShepherdTests),
    ]
}
#endif
