#if !canImport(ObjectiveC)
import XCTest

extension XCRouterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XCRouterTests = [
        ("testEmptyRouter", testEmptyRouter),
        ("testEmptyRouterWithParent", testEmptyRouterWithParent),
        ("testEmptyRouterWithParentHandlingPath", testEmptyRouterWithParentHandlingPath),
        ("testEmptyRouterWithParentIgnoringParent", testEmptyRouterWithParentIgnoringParent),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(XCRouterTests.__allTests__XCRouterTests),
    ]
}
#endif
