#if !canImport(ObjectiveC)
import XCTest

extension ClosurePathHandlerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ClosurePathHandlerTests = [
        ("testClosurePathHandlerWithDifferentPathType", testClosurePathHandlerWithDifferentPathType),
    ]
}

extension RouterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RouterTests = [
        ("testEmptyRouter", testEmptyRouter),
        ("testEmptyRouterWithParent", testEmptyRouterWithParent),
        ("testEmptyRouterWithParentHandlingPath", testEmptyRouterWithParentHandlingPath),
        ("testEmptyRouterWithParentIgnoringParent", testEmptyRouterWithParentIgnoringParent),
        ("testRouterRemovingNonChildRouter", testRouterRemovingNonChildRouter),
        ("testRouterWithChildHandlerHandlingPath", testRouterWithChildHandlerHandlingPath),
        ("testRouterWithChildRouter", testRouterWithChildRouter),
        ("testRouterWithMultiplePriorityHandlers", testRouterWithMultiplePriorityHandlers),
        ("testRouterWithRemovedHandler", testRouterWithRemovedHandler),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ClosurePathHandlerTests.__allTests__ClosurePathHandlerTests),
        testCase(RouterTests.__allTests__RouterTests),
    ]
}
#endif
