default_platform :ios

platform :ios do

  desc "Runs tests"
  lane :test do
    scan
  end

  desc "Performs checks that pull requests are required to pass"
  lane :perform_pr_checks do
    test
    Dir.chdir("..") do
      # Uses `pod lib lint` over `pod spec lint` because otherwise the repo
      # will be pulled, which will fail because the tag might not have been
      # pushed yet
      sh("bundle", "exec", "pod", "lib", "lint")
    end
  end

  desc "Generates documentation using jazzy"
  lane :generate_documentation do
    jazzy
  end

end