name: PR Checks

on: [pull_request]

jobs:
  danger:
    name: Danger
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1

    - name: Read .node-version
      id: node-version
      run: echo ::set-output name=version::$(cat .node-version)
    - name: Setup Node.js ${{ steps.node-version.outputs.version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ steps.node-version.outputs.version }}

    - name: yarn install
      run: yarn install

    - name: Cache SwiftPM
      uses: actions/cache@v1
      with:
        path: .build
        key: ${{ runner.os }}-swiftpm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-swiftpm-
    - name: Build Danger and Danger Dependencies
      run: swift build --skip-update --target DangerDependencies
    - name: Run Danger
      run: swift run --skip-update danger-swift ci --danger-js-path $(yarn bin danger) --verbose
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  pod_lib_lint:
    name: pod lib lint
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1

    - name: Cache Bundler
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-bundler-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-bundler-
    - name: bundle install
      run: bundle install --deployment

    - name: pod lib lint
      run: bundle exec pod lib lint
